version: "3.8"

services:
  clash-mongo:
    image: mongo:latest
    container_name: clash-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  importer:
    build: ./importer
    depends_on:
      - clash-mongo
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "import_from_api.py"]

volumes:
  mongo-data:
